version: '3.8'

services:
  db:
    image: postgres:15
    container_name: queue_app_db
    environment:
      POSTGRES_DB: queue_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - queue_network

  redis:
    image: redis:7-alpine
    container_name: queue_app_redis
    ports:
      - "6379:6379"
    networks:
      - queue_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: queue_app_backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/queue_app
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    networks:
      - queue_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

networks:
  queue_network:
    driver: bridge